# BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    contrast = 0.8916
    brightness = 0.7
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# CLIMA E LOCALIZAÇÃO (Topo)
label {
    monitor =
    text = cmd[update:3600000] bash -c "curl -s 'wttr.in/Recife?format=%l\n%c+%C+%t' | tr -d '+'"
    color = rgba(255, 255, 255, 0.9)
    font_size = 12
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 260
    halign = center
    valign = center
}

# RELÓGIO - HORAS (Centro Superior)
label {
    monitor =
    text = cmd[update:1000] date +"%H"
    color = rgba(255, 255, 255, 1)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 75
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
}

# RELÓGIO - MINUTOS (Centro Inferior)
label {
    monitor =
    text = cmd[update:1000] date +"%M"
    color = rgba(255, 255, 255, 1)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -60
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
}

# DATA (Abaixo do relógio - Forçando o "-feira")
label {
    monitor =
    text = cmd[update:18000000] bash -c 'd=$(date +%w); dias=("Domingo" "Segunda-feira" "Terça-feira" "Quarta-feira" "Quinta-feira" "Sexta-feira" "Sábado"); echo "$(date +"%d %b"), ${dias[$d]}"'
    color = rgb(13, 202, 240)
    font_size = 14
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -190
    halign = center
    valign = center
}

# MÍDIA (Texto Simples)
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/media.sh
    color = rgba(255, 255, 255, 0.7)
    font_size = 11
    font_family = JetBrainsMono Nerd Font
    position = 0, -250
    halign = center
    valign = center
}

# CAMPO DE SENHA (Pílula Escura)
input-field {
    monitor =
    size = 200, 40
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    inner_color = rgba(0, 0, 0, 0.8)
    font_color = rgba(255, 255, 255, 0.8)
    fade_on_empty = false
    placeholder_text = <span font_family="JetBrainsMono Nerd Font" font_size="9pt">PASSWORD</span>
    hide_input = false
    position = 0, -330
    halign = center
    valign = center
    rounding = -1
}
